apiVersion: v1
kind: ConfigMap
metadata:
  name: coua
  namespace: {{ .Values.global.common_configs.namespace }}
data:
  aliyun_logs_madagascar-prod: stdout
  ROCKETMQ_TOPIC: {{ .Values.rocketmq.topic }}
  ROCKETMQ_TAG: {{ .Values.rocketmq.tag }}
  OPENTRACING_JAEGER_CONSTSAMPLER_DECISION: '{{ .Values.deploy.opentracing.enable_jaeger }}'
  OPENTRACING_JAEGER_GRPCSERVERINTERCEPTOR: '{{ .Values.deploy.opentracing.enable_jaeger }}'
  GRPC_FOSSA_HOST: {{ .Values.fossa.host }}
  GRPC_FOSSA_PORT: '{{ .Values.fossa.port }}'
  GRPC_VANGA_HOST: {{ .Values.vanga.host }}
  GRPC_VANGA_PORT: '{{ .Values.vanga.port }}'
  GRPC_ASITY_HOST: {{ .Values.asity.host }}
  GRPC_ASITY_PORT: '{{ .Values.asity.port }}'