spring:
  datasource:
    url: jdbc:mysql://root:123456@localhost:3306/guns_advanced?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      database: fossa
      uri:

rocketmq:
  accessKey:
  secretKey:
  topic: notification-event
  tag: event
  nameSrvAddr: 192.168.0.8:9876

grpc:
  coua:
    host: 127.0.0.1
    port: 12002
  port: 12003

snowflake:
  nodeId: 0