spring:
  application:
    name: fossa
  datasource:
    url: jdbc:mysql://root:123456@localhost:3306/guns_advanced?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      database: fossa
      uri: mongodb://root:05GEJ9k7heSCM3E@dds-2ze9a184c36df9441710-pub.mongodb.rds.aliyuncs.com:3717/admin?replicaSet=mgset-31197927&readPreference=secondaryPreferred&maxIdleTimeMS=300000

madagascar:
  short-code-base: https://staging.keepreal.cn/s/%s

rocketmq:
  notification:
    accessKey: xxx
    secretKey: xxx
    topic: notification-event
    tag: event
    nameSrvAddr: 127.0.0.1:9876
  feed:
    accessKey: xxx
    secretKey: xxx
    topic: feed-event
    tag: event
    nameSrvAddr: 127.0.0.1:9876
  transaction:
    accessKey: 1
    secretKey: 2
    nameSrvAddr: 127.0.0.1:9876
    topic: transaction-event
    groupId: GID-fossa-transaction
    tag: event

grpc:
  coua:
    host: 127.0.0.1
    port: 12002
  vanga:
    host: 127.0.0.1
    port: 12006
  port: 12003

snowflake:
  nodeId: 0

opentracing:
  jaeger:
    grpc-server-interceptor: false
    const-sampler:
      decision: false