spring:
  application:
    name: coua
  datasource:
    url: jdbc:mysql://root:123456@localhost:3306/guns_advanced?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  redis:
    host: 127.0.0.1
    port: 6379

rocketmq:
  island:
    accessKey: xxx
    secretKey: xxx
    topic: island-event
    tag: event
    nameSrvAddr: 127.0.0.1:9876
  user:
    accessKey: xxx
    secretKey: xxx
    topic: user-event
    tag: event
    nameSrvAddr: 127.0.0.1:9876
  notification:
    accessKey: xxx
    secretKey: xxx
    topic: notification-event
    tag: event
    nameSrvAddr: 127.0.0.1:9876
    groupId: GID-coua-notification-default
  transaction:
    accessKey: xxx
    secretKey: xxx
    topic: transaction-event
    tag: event
    nameSrvAddr: 127.0.0.1:9876

grpc:
  fossa:
    host: 127.0.0.1
    port: 12003
  vanga:
    host: 127.0.0.1
    port: 12006
  asity:
    host: 127.0.0.1
    port: 12007
  port: 12002

snowflake:
  nodeId: 0

opentracing:
  jaeger:
    grpc-server-interceptor: false
    const-sampler:
      decision: false

server:
  port: 8090

aliyun:
  sms:
    access-key:
    access-secret:
    template-id: SMS_200712472