spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306
    driver-class-name: com.mysql.cj.jdbc.Driver

rocketmq:
  accessKey: "xxx"
  secretKey: "xxx"
  nameSrvAddr: "xxx"