spring:
  datasource:
    url: jdbc:mysql://root:123456@localhost:3306/guns_advanced?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    driver-class-name: com.mysql.cj.jdbc.Driver

rocketmq:
  accessKey: xxx
  secretKey: xxx
  topic: notification-event
  tag: event
  nameSrvAddr: 127.0.0.1:9876

grpc:
  fossa:
    host: 127.0.0.1
    port: 12003
  port: 12002

snowflake:
  nodeId: 0