spring:
  application:
    name: coua
  datasource:
    url: jdbc:mysql://kr_admin:gYvi89kGKJoqZbzk@rm-2ze0p9v29ef1p05us6o.mysql.rds.aliyuncs.com:3306/coua?autoReconnect=true&useUnicode=true&characterEncoding=utf8&character_set_server=utf8mb4&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  redis:
    host: 127.0.0.1
    port: 6379

rocketmq:
  island:
    accessKey: xxx
    secretKey: xxx
    topic: island-event
    tag: event
    nameSrvAddr: 127.0.0.1:9876
  user:
    accessKey: xxx
    secretKey: xxx
    topic: user-event
    tag: event
    nameSrvAddr: 127.0.0.1:9876
  notification:
    accessKey: xxx
    secretKey: xxx
    topic: notification-event
    tag: event
    nameSrvAddr: 127.0.0.1:9876
    groupId: GID-coua-notification-default
  transaction:
    accessKey: xxx
    secretKey: xxx
    topic: transaction-event
    tag: event
    nameSrvAddr: 127.0.0.1:9876

grpc:
  fossa:
    host: 127.0.0.1
    port: 12003
  vanga:
    host: 127.0.0.1
    port: 12006
  asity:
    host: 127.0.0.1
    port: 12007
  port: 12002

snowflake:
  nodeId: 0

opentracing:
  jaeger:
    grpc-server-interceptor: false
    const-sampler:
      decision: false

server:
  port: 8090

aliyun:
  sms:
    access-key:
    access-secret:
    template-id: SMS_200712472
    international-template-id: SMS_201653094