# Default values for madagascar-cn-prod.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  acr:
    acr_secret_name: keepreal-acr-secret
  common_configs:
    namespace: keepreal-prod
    lark:
      webhook: https://open.feishu.cn/open-apis/bot/hook/d42eb11f-8804-4836-9ce8-881074c4077e
    replicas:
      lemur: 2
      baobob: 2
      brookesia: 2
      coua: 2
      fossa: 2
      indri: 2
      mantella: 2
      marty: 2
      tenrecs: 2
      vanga: 2
      asity: 2
    short_code_base: https://islands.keepreal.cn/s/%s
    image_host: https://images.keepreal.cn
    html_host: https://h5.tiaodaoapp.com
    wechat_pay:
      callback_address: https://islands.keepreal.cn/api/v1/orders/wechat/callback
      refund_callback_address: https://islands.keepreal.cn/api/v1/orders/wechat/refund/callback
  images:
    lemur:
      name: registry-vpc.cn-beijing.aliyuncs.com/keepreal/lemur
      tag: 1.2.6
      imagePullPolicy: Always
    baobob:
      name: registry-vpc.cn-beijing.aliyuncs.com/keepreal/baobob
      tag: 1.1.0
      imagePullPolicy: Always
    brookesia:
      name: registry-vpc.cn-beijing.aliyuncs.com/keepreal/brookesia
      tag: 1.0.3
      imagePullPolicy: Always
    coua:
      name: registry-vpc.cn-beijing.aliyuncs.com/keepreal/coua
      tag: 1.1.0
      imagePullPolicy: Always
    fossa:
      name: registry-vpc.cn-beijing.aliyuncs.com/keepreal/fossa
      tag: 1.1.0
      imagePullPolicy: Always
    indri:
      name: registry-vpc.cn-beijing.aliyuncs.com/keepreal/indri
      tag: 1.0.3
      imagePullPolicy: Always
    mantella:
      name: registry-vpc.cn-beijing.aliyuncs.com/keepreal/mantella
      tag: 1.1.0
      imagePullPolicy: Always
    marty:
      name: registry-vpc.cn-beijing.aliyuncs.com/keepreal/marty
      tag: 1.0.6
      imagePullPolicy: Always
    tenrecs:
      name: registry-vpc.cn-beijing.aliyuncs.com/keepreal/tenrecs
      tag: 1.0.5
      imagePullPolicy: Always
    vanga:
      name: registry-vpc.cn-beijing.aliyuncs.com/keepreal/vanga
      tag: 1.1.3
      imagePullPolicy: Always
    settler:
      name: registry-vpc.cn-beijing.aliyuncs.com/keepreal/settler
      tag: 1.1.0
      imagePullPolicy: Always
    reconciliation:
      name: registry-vpc.cn-beijing.aliyuncs.com/keepreal/reconciliation
      tag: 1.0.1
      imagePullPolicy: Always
    asity:
      name: registry-vpc.cn-beijing.aliyuncs.com/keepreal/asity
      tag: 1.0.4
      imagePullPolicy: Always
    statistics:
      name: registry-vpc.cn-beijing.aliyuncs.com/keepreal/statistics
      tag: 1.0.0
      imagePullPolicy: Always

deploy:
  enable_http: false
  ssl:
    cert_id: 1398284016177859_1720332b91b_1749325862_1022387165
  slb:
    id: lb-2ze2ccvjnvhdwq8nkqd66