apiVersion: v1
kind: ConfigMap
metadata:
  name: vanga
  namespace: {{ .Values.global.common_configs.namespace }}
data:
  aliyun_logs_madagascar-prod: stdout
  ROCKETMQ_NOTIFICATION_TOPIC: {{ .Values.rocketmq.notification.topic }}
  ROCKETMQ_NOTIFICATION_TAG: {{ .Values.rocketmq.notification.tag }}
  WECHATPAY_APPID: {{ .Values.wechat_pay.app_id }}
  WECHATPAY_MERCHANTID: {{ .Values.wechat_pay.merchant_id }}
  WECHATPAY_CALLBACKADDRESS: {{ .Values.wechat_pay.callback_address }}
  WECHATPAY_CERTPATH: {{ .Values.wechat_pay.cert_path }}
  SPRING_REDIS_SSL: 'false'
  OPENTRACING_JAEGER_CONSTSAMPLER_DECISION: '{{ .Values.deploy.opentracing.enable_jaeger }}'
  OPENTRACING_JAEGER_GRPCSERVERINTERCEPTOR: '{{ .Values.deploy.opentracing.enable_jaeger }}'