apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemur
  namespace: {{ .Values.common_configs.namespace }}
spec:
  replicas: {{ .Values.common_configs.replicas }}
  selector:
    matchLabels:
      app: lemur
  template:
    metadata:
      labels:
        app: lemur
    spec:
      initContainers:
        - name: sysctl
          command:
            - sh
            - -c
            - sysctl -w net.ipv4.tcp_keepalive_time=600; sysctl -w net.ipv4.tcp_keepalive_intvl=30; sysctl -w net.ipv4.tcp_keepalive_probes=10
          image: alpine:3.6
          imagePullPolicy: IfNotPresent
          resources: {}
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
      imagePullSecrets:
        - name: {{ .Values.global.acr.acr_secret_name }}
      containers:
        - name: lemur
          image: {{ .Values.images.lemur.name }}:{{ .Values.images.lemur.tag }}
          imagePullPolicy: {{ .Values.images.lemur.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: lemur
          resources:
            limits:
              memory: {{ .Values.common_configs.memory }}
            requests:
              cpu: {{ .Values.common_configs.cpu }}
              memory: {{ .Values.common_configs.memory }}
          ports:
            - containerPort: 8081
              name: lemur-http
---
apiVersion: v1
kind: Service
metadata:
  name: lemur
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: lemur-http
  selector:
    app: lemur