spring:
  data:
    mongodb:
      database: tenrecs
      uri: mongodb://root:password@127.0.0.1:27017

rocketmq:
  accessKey:
  secretKey:
  nameSrvAddr: localhost:9876
  topic: notification-event
  groupId: GID-tenrecs-default
  tag: event

grpc:
  port: 12004

snowflake:
  nodeId: 0