spring:
  data:
    mongodb:
      database: tenrecs
      uri: mongodb://127.0.0.1:27017

rocketmq:
  accessKey: xxx
  secretKey: xxx
  nameSrvAddr: 127.0.0.1:9876
  topic: notification-event
  groupId: GID-tenrecs-default
  tag: event

grpc:
  port: 12004

snowflake:
  nodeId: 0