version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin registry.cn-beijing.aliyuncs.com

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      
      # run tests!
      - run: gradle indri:dockerpushstaging


workflows:
  version: 2
  build-with-tests:
    jobs:
      - build:
          context:
            - develop
          filters:
            branches:
              only:
                - feature/sli/ci