spring:
  application:
    name: indri

aliyun-oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKey: 123
  accessSecret: 123
  bucketName: kr-thumbnail-staging-cn2-01

grpc:
  port: 12000

deploy:
  opentrace:
    grpc-server:
      enabled: false