apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-lb
  namespace: {{ .Values.global.common_configs.namespace }}
  labels:
    app: nginx-ingress-lb
  annotations:
    # 指明SLB实例地址类型为私网类型
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
    # 指定网络类型
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-network-type: vpc
    # 修改为您的私网SLB实例ID
    service.beta.kubernetes.io/alicloud-loadbalancer-id: {{ .Values.deploy.slb.id }}
    # 是否自动创建SLB端口监听（会覆写已有端口监听），也可手动创建端口监听
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: 'true'
    # 配置https
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-protocol-port: http:80,https:443
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-cert-id: {{ .Values.deploy.ssl.cert_id }}
spec:
  type: LoadBalancer
  # route traffic to other nodes
  externalTrafficPolicy: "Cluster"
  ports:
  {{ if .Values.deploy.enable_http }}
    - port: 80
      name: http
      targetPort: lemur-http
  {{ end }}
    - port: 443
      name: https
      targetPort: lemur-http
  selector:
    app: lemur