apiVersion: v1
kind: ConfigMap
metadata:
  name: coua
  namespace: {{ .Values.common_configs.namespace }}
data:
  ROCKETMQ_NAMESRVADDR: {{ .Values.rocketmq.name_server_address }}
  ROCKETMQ_TOPIC: {{ .Values.rocketmq.topic }}
  ROCKETMQ_TAG: {{ .Values.rocketmq.tag }}
  OPENTRACING_JAEGER_CONSTSAMPLER_DECISION: '{{ .Values.deploy.opentracing.enable_jaeger }}'
  OPENTRACING_JAEGER_GRPCSERVERINTERCEPTOR: '{{ .Values.deploy.opentracing.enable_jaeger }}'