# Default values for test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

common_configs:
  memory: 2.5Gi
  cpu: 500m

mongodb:
  database: tenrecs

rocketmq:
  notification:
    topic: notification-event
    group_id: GID-tenrecs-notification-default
    tag: event
  feed:
    topic: feed-event
    group_id: GID-tenrecs-feed-default
    tag: event
deploy:
  opentracing:
    enable_jaeger: false