# Default values for test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

common_configs:
  memory: 2.5Gi
  cpu: 500m

fossa:
  host: fossa
  port: 6565

vanga:
  host: vanga
  port: 6565

asity:
  host: asity
  port: 6565

rocketmq:
  notification:
    topic: notification-event
    tag: event
  island:
    topic: island-event
    tag: event

redis:
  port: 6379

deploy:
  opentracing:
    enable_jaeger: false