grpc:
  coua:
    host: 127.0.0.1
    port: 12002
  fossa:
    host: 127.0.0.1
    port: 12003
  asity:
    host: 127.0.0.1
    port: 12007

rocketmq:
  notification:
    accessKey: 1
    secretKey: 2
    nameSrvAddr: localhost:9876
    topic: notification-event
    groupId: GID-brookesia-default
    tag: event
  feed:
    accessKey: 1
    secretKey: 2
    nameSrvAddr: localhost:9876
    topic: feed-event
    groupId: GID-brookesia-default
    tag: event
  chat:
    accessKey: 1
    secretKey: 2
    nameSrvAddr: localhost:9876
    topic: chat-event
    groupId: GID-marty-chat-default
    tag: event

umeng:
  androidAppKey: xxx
  androidAppMasterSecret: xxx
  url: xxx

spring:
  application:
    name: marty
  main:
    web-application-type: NONE
  redis:
    host: localhost

jpush:
  appKey: xxx000xxx000xxx000xxx000
  appSecret: xxx000xxx000xxx000xxx000