grpc:
  coua:
    host: 127.0.0.1
    port: 12002
  fossa:
    host: 127.0.0.1
    port: 12003

rocketmq:
  notification:
    accessKey: 1
    secretKey: 2
    nameSrvAddr: localhost:9876
    topic: notification-event
    groupId: GID-brookesia-default
    tag: event
  feed:
    accessKey: 1
    secretKey: 2
    nameSrvAddr: localhost:9876
    topic: feed-event
    groupId: GID-brookesia-default
    tag: event

umeng:
  androidAppKey: xxx
  androidAppMasterSecret: xxx
  url: xxx

spring:
  application:
    name: marty
  main:
    web-application-type: NONE
  redis:
    redisson:
      config: classpath:redisson.yml

jpush:
  appKey: xxx
  appSecret: xxx