apiVersion: v1
kind: ConfigMap
metadata:
  name: asity
  namespace: {{ .Values.global.common_configs.namespace }}
data:
  aliyun_logs_madagascar-prod: stdout
  OPENTRACING_JAEGER_CONSTSAMPLER_DECISION: '{{ .Values.deploy.opentracing.enable_jaeger }}'
  OPENTRACING_JAEGER_GRPCSERVERINTERCEPTOR: '{{ .Values.deploy.opentracing.enable_jaeger }}'
  ROCKETMQ_TOPIC: {{ .Values.rocketmq.topic }}
  ROCKETMQ_GROUPID: {{ .Values.rocketmq.group_id }}
  ROCKETMQ_TAG: {{ .Values.rocketmq.tag }}