apiVersion: v1
kind: ConfigMap
metadata:
  name: baobob
  namespace: {{ .Values.global.common_configs.namespace }}
data:
  aliyun_logs_madagascar-prod: stdout
  WECHAT_OAUTH_HOST: {{ .Values.wechat.host }}
  GRPC_COUA_HOST: {{ .Values.coua.host }}
  GRPC_COUA_PORT: '{{ .Values.coua.port }}'
  GRPC_INDRI_HOST: {{ .Values.indri.host }}
  GRPC_INDRI_PORT: '{{ .Values.indri.port }}'
  JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS: '{{ .Values.jwt.access_token_validity }}'
  JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS: '{{ .Values.jwt.refresh_token_validity }}'
  OPENTRACING_JAEGER_CONSTSAMPLER_DECISION: '{{ .Values.deploy.opentracing.enable_jaeger }}'
  OPENTRACING_JAEGER_GRPCSERVERINTERCEPTOR: '{{ .Values.deploy.opentracing.enable_jaeger }}'
  SPRING_REDIS_PORT: '{{ .Values.redis.port }}'
  WECHAT_MP_SERVERTOKEN: {{ .Values.wechat.mp.server_token }}