grpc:
  coua:
    host: 127.0.0.1
    port: 12002
  baobob:
    host: 127.0.0.1
    port: 12001
  indri:
    host: 127.0.0.1
    port: 12000
  fossa:
    host: 127.0.0.1
    port: 12003
  tenrecs:
    host: 127.0.0.1
    port: 12004
  mantella:
    host: 127.0.0.1
    port: 12005
  vanga:
    host: 127.0.0.1
    port: 12006

system-notification:
  name: test-user
  portrait-image-uri: 123.jpg
  content: hello, there.

spring:
  application:
    name: lemur
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  cache:
    jcache:
      config: ehcache-3.xml

security:
  oauth2:
    client:
      client-id: lemur
      client-secret: secret
    resource:
      token-info-uri: http://baobob:12001/oauth/check_token
    basic:
      enabled: false

server:
  port: 8081
  tomcat:
    max-threads: 200
  connection-timeout: 15s

rocketmq:
  stats-event:
    accessKey: 1
    secretKey: 2
    topic: stats-event
    tag: event
    nameSrvAddr: 192.168.0.4:9876

opentracing:
  jaeger:
    const-sampler:
      decision: false

general:
  singleOfficialIslandId: "6668436831391973376"
  officialIslandIdList:
    - "6668436831391973376"
  android-upgrade-strategy: Stochastic
  android-upgrade-ratio: 100
  sensitive-words-file-path: /app/good-dictionary.txt

client:
  android:
    setupInfo:
      version: 1
      address: https://kr-thumbnail-staging-cn2-01.oss-cn-beijing.aliyuncs.com/app-debug02.apk
    versionInfoMap:
      1:
        a360: false
        oppo: false
        vivo: false
        xiaomi: false
        huawei: false
        baidu: false
        wandoujia: false
        yingyongbao: false
        lianxiang: false
        kr: false
    updateInfoMap:
      1:
        currentVersion: 1
        nextVersion: 1
        address: https://kr-thumbnail-staging-cn2-01.oss-cn-beijing.aliyuncs.com/app-debug02.apk
        message: first version
        shouldForce: false
  ios:
    versionInfoMap:
      100:
        island-feed-loop-interval: 10
        myIslands-page-size: 100
        message-loop-interval: 10
        guest-page-size: 5
        island-check-interval: 10
        config-timeout: 1000
        audit: false
    updateInfoMap:
      100:
        currentVersion: 100
        nextVersion: 100

aliyun-oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKey: 123
  accessSecret: 123
  bucketName: kr-thumbnail-staging-cn2-01
  expireTimeInSeconds: 30