grpc:
  coua:
    host: 127.0.0.1
    port: 12002
  baobob:
    host: 127.0.0.1
    port: 12001
  indri:
    host: 127.0.0.1
    port: 12000
  fossa:
    host: 127.0.0.1
    port: 12003
  tenrecs:
    host: 127.0.0.1
    port: 12004

system-notification:
  name: test-user
  portrait-image-uri: 123.jpg
  content: hello, there.

spring:
  application:
    name: lemur
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  cache:
    jcache:
      config: ehcache-3.xml

security:
  oauth2:
    client:
      client-id: lemur
      client-secret: secret
    resource:
      jwt:
        key-value: thisisatopsecret
    basic:
      enabled: false

server:
  port: 8081
  tomcat:
    max-threads: 200
  connection-timeout: 15s

rocketmq:
  stats-event:
    accessKey: 1
    secretKey: 2
    topic: stats-event
    tag: event
    nameSrvAddr: 192.168.0.4:9876

opentracing:
  jaeger:
    const-sampler:
      decision: false

general:
  singleOfficialIslandId: "6668436831391973376"
  officialIslandIdList:
    - "6668436831391973376"

client:
  android:
    setup:
      version: 1
      address: https://kr-thumbnail-staging-cn2-01.oss-cn-beijing.aliyuncs.com/app-debug02.apk