apiVersion: v1
kind: ConfigMap
metadata:
  name: marty
  namespace: {{ .Values.global.common_configs.namespace }}
data:
  aliyun_logs_madagascar-prod: stdout
  GRPC_COUA_HOST: {{ .Values.coua.host }}
  GRPC_COUA_PORT: '{{ .Values.coua.port }}'
  GRPC_FOSSA_HOST: {{ .Values.fossa.host }}
  GRPC_FOSSA_PORT: '{{ .Values.fossa.port }}'
  ROCKETMQ_NOTIFICATION_NAMESRVADDR: {{ .Values.rocketmq.notification.name_server_address }}
  ROCKETMQ_NOTIFICATION_TOPIC: {{ .Values.rocketmq.notification.topic }}
  ROCKETMQ_NOTIFICATION_GROUPID: {{ .Values.rocketmq.notification.group_id }}
  ROCKETMQ_NOTIFICATION_TAG: {{ .Values.rocketmq.notification.tag }}
  ROCKETMQ_FEED_NAMESRVADDR: {{ .Values.rocketmq.feed.name_server_address }}
  ROCKETMQ_FEED_TOPIC: {{ .Values.rocketmq.feed.topic }}
  ROCKETMQ_FEED_GROUPID: {{ .Values.rocketmq.feed.group_id }}
  ROCKETMQ_FEED_TAG: {{ .Values.rocketmq.feed.tag }}
  UMENG_URL: {{ .Values.ument.url }}
  OPENTRACING_JAEGER_CONSTSAMPLER_DECISION: '{{ .Values.deploy.opentracing.enable_jaeger }}'
  OPENTRACING_JAEGER_GRPCSERVERINTERCEPTOR: '{{ .Values.deploy.opentracing.enable_jaeger }}'