spring:
  application:
    name: settler
  datasource:
    url: jdbc:mysql://root:pass@host:port
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      database: workflow
      uri: mongodb://root:pass@host:port
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    ssl: false

lark:
  webhook: https://open.feishu.cn/open-apis/bot/hook/61a6dd4a8ffe4d3f9d81ee418d26cb73

executor:
  threads: 20

wechat-pay:
  app-id: xxx
  merchant-id: xxx
  merchant-key: xxx
  callback-address: https://staging.keepreal.cn/api/v1/orders/wechat/callback
  refund-callback-address: https://staging.keepreal.cn/api/v1/orders/wechat/refund/callback
  cert-path: /app/apiclient_cert.p12
  host-ip: 127.0.0.1

workflow:
  type: settler-daily