apiVersion: v1
kind: ConfigMap
metadata:
  name: reconsiliation
  namespace: {{ .Values.global.common_configs.namespace }}
data:
  aliyun_logs_madagascar-prod: stdout
  SPRING_DATA_MONGODB_DATABASE: {{ .Values.mongodb.database }}
  SPRING_REDIS_PORT: '{{ .Values.redis.port }}'