wechat:
  oauth:
    host: https://api.weixin.qq.com
    app-id:
    app-secret:

grpc:
  port: 12001
  coua:
    host: 192.168.0.7
    port: 12002

jwt:
  token-secret: thisisatopsecret
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 6000
  client-secret: secret