spring:
  application:
    name: baobob
  redis:
    host: 127.0.0.1
    port: 6379
    #password: GcrkNYTcST4PzlV@
    #ssl: false

wechat:
  oauth:
    host: https://api.weixin.qq.com
    app-id:
    app-secret:
  mp:
    host: https://api.weixin.qq.com
    app-id:
    app-secret:
    server-token:
    expiration-in-sec: 60

grpc:
  port: 12001
  coua:
    host: 127.0.0.1
    port: 12002
  indri:
    host: 127.0.0.1
    port: 12000

jwt:
  token-secret: thisisatopsecret
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 6000
  client-secret: secret

opentracing:
  jaeger:
    grpc-server-interceptor: false
    const-sampler:
      decision: false

loginsetting:
  enable-adminLogin: true