# Default values for test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

common_configs:
  replicas: 1
  memory: 2.5Gi
  cpu: 500m

rocketmq:
  notification:
    topic: notification-event
    group_id: GID-mantella-default
    tag: event
  feed:
    topic: feed-event
    group_id: GID-mantella-default
    tag: event

coua:
  host: coua
  port: 6565

fossa:
  host: fossa
  port: 6565

mongodb:
  database: mantella

deploy:
  opentracing:
    enable_jaeger: false