apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: angonoka
  namespace: {{ .Values.global.common_configs.namespace }}
spec:
  replicas: {{ .Values.global.common_configs.replicas.angonoka }}
  selector:
    matchLabels:
      app: angonoka
  serviceName: angonoka
  template:
    metadata:
      annotations:
        config.linkerd.io/init-image: registry-vpc.cn-beijing.aliyuncs.com/keepreal/linkerd-proxy-init
        config.linkerd.io/init-image-version: v1.3.2
        config.linkerd.io/proxy-image: registry-vpc.cn-beijing.aliyuncs.com/keepreal/linkerd-proxy
        config.linkerd.io/proxy-image-version: stable-2.7.1
        linkerd.io/inject: enabled
      labels:
        app: angonoka
    spec:
      initContainers:
        - name: sysctl
          command:
            - sh
            - -c
            - sysctl -w net.ipv4.tcp_keepalive_time=600; sysctl -w net.ipv4.tcp_keepalive_intvl=30; sysctl -w net.ipv4.tcp_keepalive_probes=10
          image: alpine:3.6
          imagePullPolicy: IfNotPresent
          resources: {}
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
      imagePullSecrets:
        - name: {{ .Values.global.acr.acr_secret_name }}
      containers:
        - name: angonoka
          image: {{ .Values.global.images.angonoka.name }}:{{ .Values.global.images.angonoka.tag }}
          imagePullPolicy: {{ .Values.global.images.angonoka.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: angonoka
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  key: angonoka-connection-string
                  name: aliyun-rdb
            - name: RESTART
              value: "1"
          resources:
            limits:
              memory: {{ .Values.common_configs.memory }}
            requests:
              cpu: {{ .Values.common_configs.cpu }}
              memory: {{ .Values.common_configs.memory }}
          ports:
            - containerPort: 12008
              name: angonoka-grpc
        {{ if .Values.deploy.opentracing.enable_jaeger }}
        - name: jaeger-agent
          image: jaegertracing/jaeger-agent:1.17.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
              name: zk-compact-trft
              protocol: UDP
            - containerPort: 5778
              name: config-rest
              protocol: TCP
            - containerPort: 6831
              name: jg-compact-trft
              protocol: UDP
            - containerPort: 6832
              name: jg-binary-trft
              protocol: UDP
            - containerPort: 14271
              name: admin-http
              protocol: TCP
          args:
            - --reporter.tchannel.host-port=simplest-collector-headless.keepreal-prod.svc:14267
            - --reporter.type=tchannel
        {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: angonoka
spec:
  type: ClusterIP
  ports:
    - port: 6565
      targetPort: angonoka-grpc
  selector:
    app: angonoka