apiVersion: v1
kind: ConfigMap
metadata:
  name: angonoka
  namespace: {{ .Values.global.common_configs.namespace }}
data:
  aliyun_logs_madagascar-prod: stdout
  ACTIVITY_SHOWLABEL: 'false'
  OPENTRACING_JAEGER_CONSTSAMPLER_DECISION: '{{ .Values.deploy.opentracing.enable_jaeger }}'
  OPENTRACING_JAEGER_GRPCSERVERINTERCEPTOR: '{{ .Values.deploy.opentracing.enable_jaeger }}'