spring:
  application:
    name: vanga
  datasource:
    url: jdbc:mysql://root:pass@localhost:3306/coua
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  redis:
    host: retail01d
    port: 6379
    password: pass
    ssl: false

wechat-pay:
  app-id:
  merchant-id:
  merchant-key:
  callback-address: http://123.57.72.117:8081/api/v1/orders/wechat/callback
  cert-path: /Users/sli/development/madagascar/vanga/src/main/resources/apiclient_cert.pem
  host-ip: 127.0.0.1

rocketmq:
  notification:
    accessKey: xxx
    secretKey: xxx
    topic: notification-event
    tag: event
    nameSrvAddr: 127.0.0.1:9876