FROM openjdk:8-jdk-alpine
VOLUME /tmp
ENV TZ=Asia/Shanghai
ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app
COPY ${DEPENDENCY}/apiclient_cert.p12 /app
COPY ${DEPENDENCY}/appCertPublicKey_2021001189642510.crt /app
COPY ${DEPENDENCY}/alipayCertPublicKey_RSA2.crt /app
COPY ${DEPENDENCY}/alipayRootCert.crt /app
COPY ${DEPENDENCY}/start.sh /app
ENTRYPOINT ["sh", "/app/start.sh"]