apiVersion: v1
kind: ConfigMap
metadata:
  name: lemur
  namespace: {{ .Values.global.common_configs.namespace }}
data:
  aliyun_logs_madagascar-prod: stdout
  GRPC_COUA_HOST: {{ .Values.coua.host }}
  GRPC_COUA_PORT: '{{ .Values.coua.port }}'
  GRPC_BAOBOB_HOST: {{ .Values.baobob.host }}
  GRPC_BAOBOB_PORT: '{{ .Values.baobob.port }}'
  GRPC_INDRI_HOST: {{ .Values.indri.host }}
  GRPC_INDRI_PORT: '{{ .Values.indri.port }}'
  GRPC_FOSSA_HOST: {{ .Values.fossa.host }}
  GRPC_FOSSA_PORT: '{{ .Values.fossa.port }}'
  GRPC_TENRECS_HOST: {{ .Values.tenrecs.host }}
  GRPC_TENRECS_PORT: '{{ .Values.tenrecs.port }}'
  GRPC_VANGA_HOST: {{ .Values.vanga.host }}
  GRPC_VANGA_PORT: '{{ .Values.vanga.port }}'
  GRPC_MANTELLA_HOST: {{ .Values.mantella.host }}
  GRPC_MANTELLA_PORT: '{{ .Values.mantella.port }}'
  GRPC_ASITY_HOST: {{ .Values.asity.host }}
  GRPC_ASITY_PORT: '{{ .Values.asity.port }}'
  GRPC_HOOPOE_HOST: {{ .Values.hoopoe.host }}
  GRPC_HOOPOE_PORT: '{{ .Values.hoopoe.port }}'
  GRPC_ANGONOKA_HOST: {{ .Values.angonoka.host }}
  GRPC_ANGONOKA_PORT: '{{ .Values.angonoka.port }}'
  GRPC_HAWKSBILL_HOST: {{ .Values.hawksbill.host }}
  GRPC_HAWKSBILL_PORT: '{{ .Values.hawksbill.port }}'
  SPRING_SERVLET_MULTIPART_MAXFILESIZE: {{ .Values.file.max_file_size }}
  SPRING_SERVLET_MULTIPART_MAXREQUESTSIZE: {{ .Values.file.max_request_size }}
  SYSTEMNOTIFICATION_NAME: {{ .Values.system_notification.name }}
  SYSTEMNOTIFICATION_CONTENT: {{ .Values.system_notification.content }}
  SYSTEMNOTIFICATION_PORTRAITIMAGEURI: {{ .Values.system_notification.portrait_image_uri }}
  ROCKETMQ_STATSEVENT_TOPIC: {{ .Values.rocketmq.topic }}
  ROCKETMQ_STATSEVENT_TAG: {{ .Values.rocketmq.tag }}
  OPENTRACING_JAEGER_CONSTSAMPLER_DECISION: '{{ .Values.deploy.opentracing.enable_jaeger }}'
  SECURITY_OAUTH2_RESOURCE_TOKENINFOURI: {{ .Values.security.oauth2.resource.token_info_uri }}
  SPRING_REDIS_PORT: '{{ .Values.redis.port }}'
  ALIYUNOSS_EXPIRETIMEINSECONDS: '{{ .Values.aliyun_oss.expire_time_in_seconds }}'
  ALIYUNVOD_REGIONID: {{ .Values.aliyun_vod.region_id }}

  GENERAL_ANDROIDUPGRADESTRATEGY: '{{ .Values.release.strategy }}'
  GENERAL_ANDROIDUPGRADERATIO: '{{ .Values.release.ratio }}'
  CLIENT_ANDROID_SETUPINFO_VERSION: '{{ .Values.client.android.setup_info.version }}'
  CLIENT_ANDROID_SETUPINFO_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_IOS_HTMLHOSTNAME: {{ .Values.global.common_configs.html_host }}

  CLIENT_ANDROID_UPDATEINFOMAP_1_CURRENTVERSION: '1'
  CLIENT_ANDROID_UPDATEINFOMAP_1_NEXTVERSION: '171'
  CLIENT_ANDROID_UPDATEINFOMAP_1_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_1_MESSAGE: '更新了群组和聊天功能'
  CLIENT_ANDROID_UPDATEINFOMAP_1_SHOULDFORCE: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_110_CURRENTVERSION: '110'
  CLIENT_ANDROID_UPDATEINFOMAP_110_NEXTVERSION: '171'
  CLIENT_ANDROID_UPDATEINFOMAP_110_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_110_MESSAGE: '更新了群组和聊天功能'
  CLIENT_ANDROID_UPDATEINFOMAP_110_SHOULDFORCE: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_111_CURRENTVERSION: '111'
  CLIENT_ANDROID_UPDATEINFOMAP_111_NEXTVERSION: '171'
  CLIENT_ANDROID_UPDATEINFOMAP_111_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_111_MESSAGE: '更新了群组和聊天功能'
  CLIENT_ANDROID_UPDATEINFOMAP_111_SHOULDFORCE: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_120_CURRENTVERSION: '120'
  CLIENT_ANDROID_UPDATEINFOMAP_120_NEXTVERSION: '171'
  CLIENT_ANDROID_UPDATEINFOMAP_120_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_120_MESSAGE: '更新了群组和聊天功能'
  CLIENT_ANDROID_UPDATEINFOMAP_120_SHOULDFORCE: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_121_CURRENTVERSION: '121'
  CLIENT_ANDROID_UPDATEINFOMAP_121_NEXTVERSION: '171'
  CLIENT_ANDROID_UPDATEINFOMAP_121_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_121_MESSAGE: '更新了群组和聊天功能'
  CLIENT_ANDROID_UPDATEINFOMAP_121_SHOULDFORCE: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_130_CURRENTVERSION: '130'
  CLIENT_ANDROID_UPDATEINFOMAP_130_NEXTVERSION: '171'
  CLIENT_ANDROID_UPDATEINFOMAP_130_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_130_MESSAGE: '支持长文、多图、音频、视频啦, 增加了用户引导，使用体验更好了'
  CLIENT_ANDROID_UPDATEINFOMAP_130_SHOULDFORCE: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_131_CURRENTVERSION: '131'
  CLIENT_ANDROID_UPDATEINFOMAP_131_NEXTVERSION: '171'
  CLIENT_ANDROID_UPDATEINFOMAP_131_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_131_MESSAGE: ''
  CLIENT_ANDROID_UPDATEINFOMAP_131_SHOULDFORCE: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_140_CURRENTVERSION: '140'
  CLIENT_ANDROID_UPDATEINFOMAP_140_NEXTVERSION: '171'
  CLIENT_ANDROID_UPDATEINFOMAP_140_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_140_MESSAGE: ''
  CLIENT_ANDROID_UPDATEINFOMAP_140_SHOULDFORCE: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_141_CURRENTVERSION: '141'
  CLIENT_ANDROID_UPDATEINFOMAP_141_NEXTVERSION: '171'
  CLIENT_ANDROID_UPDATEINFOMAP_141_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_141_MESSAGE: ''
  CLIENT_ANDROID_UPDATEINFOMAP_141_SHOULDFORCE: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_150_CURRENTVERSION: '150'
  CLIENT_ANDROID_UPDATEINFOMAP_150_NEXTVERSION: '171'
  CLIENT_ANDROID_UPDATEINFOMAP_150_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_150_MESSAGE: ''
  CLIENT_ANDROID_UPDATEINFOMAP_150_SHOULDFORCE: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_151_CURRENTVERSION: '151'
  CLIENT_ANDROID_UPDATEINFOMAP_151_NEXTVERSION: '171'
  CLIENT_ANDROID_UPDATEINFOMAP_151_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_151_MESSAGE: ''
  CLIENT_ANDROID_UPDATEINFOMAP_151_SHOULDFORCE: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_152_CURRENTVERSION: '152'
  CLIENT_ANDROID_UPDATEINFOMAP_152_NEXTVERSION: '171'
  CLIENT_ANDROID_UPDATEINFOMAP_152_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_152_MESSAGE: ''
  CLIENT_ANDROID_UPDATEINFOMAP_152_SHOULDFORCE: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_160_CURRENTVERSION: '160'
  CLIENT_ANDROID_UPDATEINFOMAP_160_NEXTVERSION: '171'
  CLIENT_ANDROID_UPDATEINFOMAP_160_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_160_MESSAGE: ''
  CLIENT_ANDROID_UPDATEINFOMAP_160_SHOULDFORCE: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_170_CURRENTVERSION: '170'
  CLIENT_ANDROID_UPDATEINFOMAP_170_NEXTVERSION: '171'
  CLIENT_ANDROID_UPDATEINFOMAP_170_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_170_MESSAGE: ''
  CLIENT_ANDROID_UPDATEINFOMAP_170_SHOULDFORCE: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_171_CURRENTVERSION: '171'
  CLIENT_ANDROID_UPDATEINFOMAP_171_NEXTVERSION: '171'
  CLIENT_ANDROID_UPDATEINFOMAP_171_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_171_MESSAGE: ''
  CLIENT_ANDROID_UPDATEINFOMAP_171_SHOULDFORCE: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_172_CURRENTVERSION: '172'
  CLIENT_ANDROID_UPDATEINFOMAP_172_NEXTVERSION: '172'
  CLIENT_ANDROID_UPDATEINFOMAP_172_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_172_MESSAGE: ''
  CLIENT_ANDROID_UPDATEINFOMAP_172_SHOULDFORCE: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_180_CURRENTVERSION: '180'
  CLIENT_ANDROID_UPDATEINFOMAP_180_NEXTVERSION: '180'
  CLIENT_ANDROID_UPDATEINFOMAP_180_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_180_MESSAGE: ''
  CLIENT_ANDROID_UPDATEINFOMAP_180_SHOULDFORCE: 'false'

  CLIENT_IOS_VERSIONINFOMAP_100_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_100_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_100_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_100_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_100_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_100_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_100_AUDIT: 'false'
  CLIENT_IOS_UPDATEINFOMAP_100_CURRENTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_100_NEXTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_100_SHOULDFORCE: 'true'
  CLIENT_IOS_VERSIONINFOMAP_110_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_110_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_110_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_110_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_110_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_110_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_110_AUDIT: 'true'
  CLIENT_IOS_UPDATEINFOMAP_110_CURRENTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_110_NEXTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_110_SHOULDFORCE: 'true'
  CLIENT_IOS_VERSIONINFOMAP_111_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_111_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_111_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_111_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_111_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_111_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_111_AUDIT: 'false'
  CLIENT_IOS_UPDATEINFOMAP_111_CURRENTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_111_NEXTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_111_SHOULDFORCE: 'true'
  CLIENT_IOS_VERSIONINFOMAP_120_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_120_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_120_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_120_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_120_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_120_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_120_AUDIT: 'false'
  CLIENT_IOS_UPDATEINFOMAP_120_CURRENTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_120_NEXTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_120_SHOULDFORCE: 'true'
  CLIENT_IOS_VERSIONINFOMAP_121_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_121_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_121_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_121_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_121_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_121_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_121_AUDIT: 'false'
  CLIENT_IOS_UPDATEINFOMAP_121_CURRENTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_121_NEXTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_121_SHOULDFORCE: 'true'
  CLIENT_IOS_VERSIONINFOMAP_130_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_130_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_130_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_130_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_130_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_130_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_130_AUDIT: 'false'
  CLIENT_IOS_UPDATEINFOMAP_130_CURRENTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_130_NEXTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_130_SHOULDFORCE: 'true'
  CLIENT_IOS_VERSIONINFOMAP_140_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_140_MYISLANDSPAGESIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_140_MESSAGELOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_140_GUESTPAGESIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_140_ISLANDCHECKINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_140_CONFIGTIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_140_AUDIT: 'false'
  CLIENT_IOS_UPDATEINFOMAP_140_CURRENTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_140_NEXTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_140_SHOULDFORCE: 'true'
  CLIENT_IOS_VERSIONINFOMAP_150_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_150_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_150_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_150_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_150_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_150_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_150_AUDIT: 'false'
  CLIENT_IOS_UPDATEINFOMAP_150_CURRENTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_150_NEXTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_150_SHOULDFORCE: 'true'
  CLIENT_IOS_VERSIONINFOMAP_160_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_160_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_160_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_160_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_160_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_160_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_160_AUDIT: 'false'
  CLIENT_IOS_UPDATEINFOMAP_160_CURRENTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_160_NEXTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_160_SHOULDFORCE: 'false'
  CLIENT_IOS_VERSIONINFOMAP_170_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_170_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_170_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_170_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_170_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_170_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_170_AUDIT: 'false'
  CLIENT_IOS_UPDATEINFOMAP_170_CURRENTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_170_NEXTVERSION: '170'
  CLIENT_IOS_UPDATEINFOMAP_170_SHOULDFORCE: 'false'
  CLIENT_IOS_VERSIONINFOMAP_172_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_172_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_172_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_172_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_172_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_172_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_172_AUDIT: 'false'
  CLIENT_IOS_UPDATEINFOMAP_172_CURRENTVERSION: '172'
  CLIENT_IOS_UPDATEINFOMAP_172_NEXTVERSION: '172'
  CLIENT_IOS_UPDATEINFOMAP_172_SHOULDFORCE: 'false'
  CLIENT_IOS_VERSIONINFOMAP_180_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_180_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_180_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_180_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_180_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_180_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_180_AUDIT: 'true'
  CLIENT_IOS_UPDATEINFOMAP_180_CURRENTVERSION: '180'
  CLIENT_IOS_UPDATEINFOMAP_180_NEXTVERSION: '180'
  CLIENT_IOS_UPDATEINFOMAP_180_SHOULDFORCE: 'false'
  CLIENT_IOS_VERSIONINFOMAP_190_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_190_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_190_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_190_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_190_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_190_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_190_AUDIT: 'false'
  CLIENT_IOS_UPDATEINFOMAP_190_CURRENTVERSION: '190'
  CLIENT_IOS_UPDATEINFOMAP_190_NEXTVERSION: '190'
  CLIENT_IOS_UPDATEINFOMAP_190_SHOULDFORCE: 'false'