apiVersion: v1
kind: ConfigMap
metadata:
  name: lemur
  namespace: {{ .Values.global.common_configs.namespace }}
data:
  aliyun_logs_madagascar-prod: stdout
  GRPC_COUA_HOST: {{ .Values.coua.host }}
  GRPC_COUA_PORT: '{{ .Values.coua.port }}'
  GRPC_BAOBOB_HOST: {{ .Values.baobob.host }}
  GRPC_BAOBOB_PORT: '{{ .Values.baobob.port }}'
  GRPC_INDRI_HOST: {{ .Values.indri.host }}
  GRPC_INDRI_PORT: '{{ .Values.indri.port }}'
  GRPC_FOSSA_HOST: {{ .Values.fossa.host }}
  GRPC_FOSSA_PORT: '{{ .Values.fossa.port }}'
  GRPC_TENRECS_HOST: {{ .Values.tenrecs.host }}
  GRPC_TENRECS_PORT: '{{ .Values.tenrecs.port }}'
  GRPC_VANGA_HOST: {{ .Values.vanga.host }}
  GRPC_VANGA_PORT: '{{ .Values.vanga.port }}'
  GRPC_MANTELLA_HOST: {{ .Values.mantella.host }}
  GRPC_MANTELLA_PORT: '{{ .Values.mantella.port }}'
  GRPC_ASITY_HOST: {{ .Values.asity.host }}
  GRPC_ASITY_PORT: '{{ .Values.asity.port }}'
  SPRING_SERVLET_MULTIPART_MAXFILESIZE: {{ .Values.file.max_file_size }}
  SPRING_SERVLET_MULTIPART_MAXREQUESTSIZE: {{ .Values.file.max_request_size }}
  SYSTEMNOTIFICATION_NAME: {{ .Values.system_notification.name }}
  SYSTEMNOTIFICATION_CONTENT: {{ .Values.system_notification.content }}
  SYSTEMNOTIFICATION_PORTRAITIMAGEURI: {{ .Values.system_notification.portrait_image_uri }}
  ROCKETMQ_STATSEVENT_TOPIC: {{ .Values.rocketmq.topic }}
  ROCKETMQ_STATSEVENT_TAG: {{ .Values.rocketmq.tag }}
  OPENTRACING_JAEGER_CONSTSAMPLER_DECISION: '{{ .Values.deploy.opentracing.enable_jaeger }}'
  SECURITY_OAUTH2_RESOURCE_TOKENINFOURI: {{ .Values.security.oauth2.resource.token_info_uri }}
  SPRING_REDIS_PORT: '{{ .Values.redis.port }}'

  GENERAL_ANDROIDUPGRADESTRATEGY: '{{ .Values.release.strategy }}'
  GENERAL_ANDROIDUPGRADERATIO: '{{ .Values.release.ratio }}'
  CLIENT_ANDROID_SETUPINFO_VERSION: '{{ .Values.client.android.setup_info.version }}'
  CLIENT_ANDROID_SETUPINFO_ADDRESS: {{ .Values.client.android.setup_info.address }}

  CLIENT_ANDROID_VERSIONINFOMAP_1_A360: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_1_OPPO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_1_VIVO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_1_XIAOMI: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_1_HUAWEI: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_1_BAIDU: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_1_WANDOUJIA: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_1_YINGYONGBAO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_1_LIANXIANG: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_1_KR: 'false'
  CLIENT_ANDROID_UPDATEINFOMAP_1_CURRENTVERSION: '1'
  CLIENT_ANDROID_UPDATEINFOMAP_1_NEXTVERSION: '121'
  CLIENT_ANDROID_UPDATEINFOMAP_1_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_1_MESSAGE: '更新了群组和聊天功能'
  CLIENT_ANDROID_UPDATEINFOMAP_1_SHOULDFORCE: 'true'
  CLIENT_ANDROID_VERSIONINFOMAP_110_A360: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_110_OPPO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_110_VIVO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_110_XIAOMI: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_110_HUAWEI: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_110_BAIDU: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_110_WANDOUJIA: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_110_YINGYONGBAO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_110_LIANXIANG: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_110_KR: 'false'
  CLIENT_ANDROID_UPDATEINFOMAP_110_CURRENTVERSION: '110'
  CLIENT_ANDROID_UPDATEINFOMAP_110_NEXTVERSION: '121'
  CLIENT_ANDROID_UPDATEINFOMAP_110_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_110_MESSAGE: '更新了群组和聊天功能'
  CLIENT_ANDROID_UPDATEINFOMAP_110_SHOULDFORCE: 'true'
  CLIENT_ANDROID_VERSIONINFOMAP_111_A360: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_111_OPPO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_111_VIVO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_111_XIAOMI: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_111_HUAWEI: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_111_BAIDU: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_111_WANDOUJIA: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_111_YINGYONGBAO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_111_LIANXIANG: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_111_KR: 'false'
  CLIENT_ANDROID_UPDATEINFOMAP_111_CURRENTVERSION: '111'
  CLIENT_ANDROID_UPDATEINFOMAP_111_NEXTVERSION: '121'
  CLIENT_ANDROID_UPDATEINFOMAP_111_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_111_MESSAGE: '更新了群组和聊天功能'
  CLIENT_ANDROID_UPDATEINFOMAP_111_SHOULDFORCE: 'true'
  CLIENT_ANDROID_VERSIONINFOMAP_120_A360: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_120_OPPO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_120_VIVO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_120_XIAOMI: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_120_HUAWEI: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_120_BAIDU: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_120_WANDOUJIA: 'true'
  CLIENT_ANDROID_VERSIONINFOMAP_120_YINGYONGBAO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_120_LIANXIANG: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_120_KR: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_120_CURRENTVERSION: '120'
  CLIENT_ANDROID_UPDATEINFOMAP_120_NEXTVERSION: '121'
  CLIENT_ANDROID_UPDATEINFOMAP_120_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_120_MESSAGE: '更新了群组和聊天功能'
  CLIENT_ANDROID_UPDATEINFOMAP_120_SHOULDFORCE: 'true'
  CLIENT_ANDROID_VERSIONINFOMAP_121_A360: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_121_OPPO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_121_VIVO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_121_XIAOMI: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_121_HUAWEI: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_121_BAIDU: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_121_WANDOUJIA: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_121_YINGYONGBAO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_121_LIANXIANG: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_121_KR: 'false'
  CLIENT_ANDROID_UPDATEINFOMAP_121_CURRENTVERSION: '121'
  CLIENT_ANDROID_UPDATEINFOMAP_121_NEXTVERSION: '121'
  CLIENT_ANDROID_UPDATEINFOMAP_121_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_121_MESSAGE: '更新了群组和聊天功能'
  CLIENT_ANDROID_UPDATEINFOMAP_121_SHOULDFORCE: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_130_A360: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_130_OPPO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_130_VIVO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_130_XIAOMI: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_130_HUAWEI: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_130_BAIDU: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_130_WANDOUJIA: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_130_YINGYONGBAO: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_130_LIANXIANG: 'false'
  CLIENT_ANDROID_VERSIONINFOMAP_130_KR: 'true'
  CLIENT_ANDROID_UPDATEINFOMAP_130_CURRENTVERSION: '130'
  CLIENT_ANDROID_UPDATEINFOMAP_130_NEXTVERSION: '130'
  CLIENT_ANDROID_UPDATEINFOMAP_130_ADDRESS: {{ .Values.client.android.setup_info.address }}
  CLIENT_ANDROID_UPDATEINFOMAP_130_MESSAGE: '1. 支持长文、多图、音频、视频啦\n2. 增加了用户引导，使用体验更好了'
  CLIENT_ANDROID_UPDATEINFOMAP_130_SHOULDFORCE: 'false'

  CLIENT_IOS_VERSIONINFOMAP_100_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_100_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_100_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_100_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_100_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_100_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_100_AUDIT: 'false'
  CLIENT_IOS_UPDATEINFOMAP_100_CURRENTVERSION: '100'
  CLIENT_IOS_UPDATEINFOMAP_100_NEXTVERSION: '130'
  CLIENT_IOS_UPDATEINFOMAP_100_SHOULDFORCE: 'true'
  CLIENT_IOS_VERSIONINFOMAP_110_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_110_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_110_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_110_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_110_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_110_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_110_AUDIT: 'true'
  CLIENT_IOS_UPDATEINFOMAP_110_CURRENTVERSION: '110'
  CLIENT_IOS_UPDATEINFOMAP_110_NEXTVERSION: '130'
  CLIENT_IOS_UPDATEINFOMAP_110_SHOULDFORCE: 'true'
  CLIENT_IOS_VERSIONINFOMAP_111_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_111_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_111_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_111_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_111_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_111_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_111_AUDIT: 'false'
  CLIENT_IOS_UPDATEINFOMAP_111_CURRENTVERSION: '111'
  CLIENT_IOS_UPDATEINFOMAP_111_NEXTVERSION: '130'
  CLIENT_IOS_UPDATEINFOMAP_111_SHOULDFORCE: 'true'
  CLIENT_IOS_VERSIONINFOMAP_120_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_120_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_120_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_120_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_120_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_120_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_120_AUDIT: 'false'
  CLIENT_IOS_UPDATEINFOMAP_120_CURRENTVERSION: '120'
  CLIENT_IOS_UPDATEINFOMAP_120_NEXTVERSION: '130'
  CLIENT_IOS_UPDATEINFOMAP_120_SHOULDFORCE: 'true'
  CLIENT_IOS_VERSIONINFOMAP_121_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_121_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_121_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_121_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_121_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_121_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_121_AUDIT: 'false'
  CLIENT_IOS_UPDATEINFOMAP_121_CURRENTVERSION: '121'
  CLIENT_IOS_UPDATEINFOMAP_121_NEXTVERSION: '130'
  CLIENT_IOS_UPDATEINFOMAP_121_SHOULDFORCE: 'true'
  CLIENT_IOS_VERSIONINFOMAP_130_ISLANDFEEDLOOPINTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_130_MYISLANDS-PAGE-SIZE: '100'
  CLIENT_IOS_VERSIONINFOMAP_130_MESSAGE-LOOP-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_130_GUEST-PAGE-SIZE: '5'
  CLIENT_IOS_VERSIONINFOMAP_130_ISLAND-CHECK-INTERVAL: '10'
  CLIENT_IOS_VERSIONINFOMAP_130_CONFIG-TIMEOUT: '1000'
  CLIENT_IOS_VERSIONINFOMAP_130_AUDIT: 'false'
  CLIENT_IOS_UPDATEINFOMAP_130_CURRENTVERSION: '130'
  CLIENT_IOS_UPDATEINFOMAP_130_NEXTVERSION: '130'
  CLIENT_IOS_UPDATEINFOMAP_130_SHOULDFORCE: 'true'

  ALIYUNOSS_EXPIRETIMEINSECONDS: '{{ .Values.aliyun_oss.expire_time_in_seconds }}'
  ALIYUNVOD_REGIONID: {{ .Values.aliyun_vod.region_id }}