# Default values for madagascar-cn-prod.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

common_configs:
  namespace: keepreal-prod

global:
  acr:
    acr_secret_name: keepreal-acr-secret

deploy:
  enable_http: false
  ssl:
    cert_id: 1398284016177859_1720332b91b_1749325862_1022387165