apiVersion: v1
kind: ConfigMap
metadata:
  name: fossa
  namespace: {{ .Values.global.common_configs.namespace }}
data:
  aliyun_logs_madagascar-prod: stdout
  SPRING_DATA_MONGODB_DATABASE: {{ .Values.mongodb.database }}
  SPRING_JPA_SHOWSQL: '{{ .Values.jpa.show_sql }}'
  GRPC_COUA_HOST: {{ .Values.coua.host }}
  GRPC_COUA_PORT: '{{ .Values.coua.port }}'
  GRPC_VANGA_HOST: {{ .Values.vanga.host }}
  GRPC_VANGA_PORT: '{{ .Values.vanga.port }}'
  ROCKETMQ_NOTIFICATION_TOPIC: {{ .Values.rocketmq.notification.topic }}
  ROCKETMQ_NOTIFICATION_TAG: {{ .Values.rocketmq.notification.tag }}
  ROCKETMQ_FEED_TOPIC: {{ .Values.rocketmq.feed.topic }}
  ROCKETMQ_FEED_TAG: {{ .Values.rocketmq.feed.tag }}
  ROCKETMQ_TRANSACTION_TOPIC: {{ .Values.rocketmq.transaction.topic }}
  ROCKETMQ_TRANSACTION_GROUPID: {{ .Values.rocketmq.transaction.group_id }}
  ROCKETMQ_TRANSACTION_TAG: {{ .Values.rocketmq.transaction.tag }}
  OPENTRACING_JAEGER_CONSTSAMPLER_DECISION: '{{ .Values.deploy.opentracing.enable_jaeger }}'
  OPENTRACING_JAEGER_GRPCSERVERINTERCEPTOR: '{{ .Values.deploy.opentracing.enable_jaeger }}'
  MADAGASCAR_SHORTCODEBASE: {{ .Values.global.common_configs.short_code_base }}