spring:
  application:
    name: settler
  datasource:
    url:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  main:
    web-application-type: none
  data:
    mongodb:
      database: workflow
      uri: 

lark:
  webhook: https://open.feishu.cn/open-apis/bot/hook/d42eb11f-8804-4836-9ce8-881074c4077e

executor:
  threads: 20

statistics:
  incre-islander-threshold: 5

workflow:
  type: statistics-daily