spring:
  application:
    name: asity
  datasource:
    url: jdbc:mysql://kr_admin:gYvi89kGKJoqZbzk@rm-2ze0p9v29ef1p05us6o.mysql.rds.aliyuncs.com:3306/asity?autoReconnect=true&useUnicode=true&characterEncoding=utf8&character_set_server=utf8mb4&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

grpc:
  port: 12007
  coua:
    host: coua
    port: 12002
rongcloud:
  app-key: 123
  app-secret: 456
  image-host: https://images.keepreal.cn

rocketmq:
  notification:
    accessKey: 1
    secretKey: 2
    nameSrvAddr: localhost:9876
    topic: notification-event
    groupId: GID-asity-default
    tag: event
  island:
    accessKey: 1
    secretKey: 2
    nameSrvAddr: localhost:9876
    topic: island-event
    groupId: GID-asity-island-default
    tag: event
  user:
    accessKey: 1
    secretKey: 2
    nameSrvAddr: localhost:9876
    topic: user-event
    groupId: GID-asity-user-default
    tag: event
  chat:
    accessKey: 1
    secretKey: 2
    nameSrvAddr: localhost:9876
    topic: chat-event
    tag: event

opentracing:
  jaeger:
    grpc-server-interceptor: false
    const-sampler:
      decision: false